name: Release
run-name: Release
on: workflow_dispatch
jobs:
  create-and-release:
    name: Create and Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Unity Library Folder
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          preset: "conventionalcommits"
          version-file: "Assets/Plugins/UBF/package.json"
          input-file: "./CHANGELOG.md"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-user-name: FVCodePublisher
          git-user-email: codepublish@futureverse.com

      - name: Find package files
        if: steps.changelog.outputs.skipped != 'true'
        run: |
          echo "Assets/Plugins/UBF.meta" >> metalist
          find "Assets/Plugins/UBF/" -name \*.meta >> metaList

      - name: Create Package
        if: steps.changelog.outputs.skipped != 'true'
        uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: UBF.unitypackage
          include-files: metaList

      - name: Create GitHub release
        if: steps.changelog.outputs.skipped != 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.changelog.outputs.version }}
          name: v${{ steps.changelog.outputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
          files: UBF.unitypackage

      - name: Return license
        uses: game-ci/unity-return-license@v2
        if: always()
